### ISSUE TITLE
Applicatiobn Quit causes Data Corruption

### ISSUE THREAD

**Issue by runette** [ViRGIS-Team/ViRGIS#197]
**Describe the bug**
Since #145 we have a problem with Application  Quit causing corruption of the gisproject.json file.

This only happens in the built application. It does not happen in the Editor. This is because Application Quit does not do anything in the editor

**To Reproduce**
Go to application in the Player and not in the editor. Press Quit

**Additional context**
This looks like we are triggering Save on gisproject on Quit and then the application is Quiting before the save is complete.

**Comment by ipnq** [comment]
yeah, didn't test it against built binary. 
I'm assuming this is related to async method call.

**Comment by runette** [comment]
I think so. I did take a quick look but cold not find where the save is
called!
