### ISSUE TITLE
Exit not working if project load fails

### ISSUE THREAD

**Issue by runette** [ViRGIS-Team/ViRGIS#241]
**Describe the bug**
If the project load fails for any reason - you cannot exit the player

**To Reproduce**
open the player without a valid gisproject.json file.

**Expected behavior**
X should close the player

**Comment by ipnq** [comment]
Is this happening in the built app?
Because in the editor I can simply stop play.

**Comment by ipnq** [comment]
I did build & run (using a misformatted gisjson file), the app runs in full screen mode and there's no X button. But I can close it from the taskbar.

**Comment by runette** [comment]
Yep. But the failure of the X button is still a bug. It should work

**Comment by runette** [comment]
Fixed in #253
